In [ ]:
#import necessary libraies
import pandas as pd
import numpy as np
import seaborn as sns
import sklearn 
from sklearn import linear_model
import sklearn.metrics as sm
import sklearn.model_selection
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
from sklearn import datasets

In [ ]:
# Load the digits dataset from scikit-learn
# Each sample is an 8x8 image of a handwritten digit (0-9)
digits = datasets.load_digits()
x= digits.data
y= digits.target

In [ ]:
# Visualize a sample digit
plt.imshow(digits.images[0], cmap='gray')
plt.title(f"Label: {digits.target[0]}")
plt.show()

In [ ]:
# Split dataset into training and testing sets
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size=0.2 , random_state=42)

In [ ]:
# Create and train logistic regression
model = linear_model.LogisticRegression(max_iter=1000)
model.fit(x_train , y_train)

In [11]:
# Predict labels for test set
y_pred = model.predict(x_test)

# Evaluate model performance
accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:\n", cm)

Accuracy: 0.97
Confusion Matrix:
 [[33  0  0  0  0  0  0  0  0  0]
 [ 0 28  0  0  0  0  0  0  0  0]
 [ 0  0 33  0  0  0  0  0  0  0]
 [ 0  0  0 33  0  1  0  0  0  0]
 [ 0  1  0  0 45  0  0  0  0  0]
 [ 0  0  1  0  0 44  1  0  0  1]
 [ 0  0  0  0  0  1 34  0  0  0]
 [ 0  0  0  0  0  1  0 33  0  0]
 [ 0  0  0  0  0  1  0  0 29  0]
 [ 0  0  0  1  0  0  0  0  1 38]]


In [ ]:
# Correlation heatmap: shows how features relate to each other and the target
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()